### ISSUE TITLE
双拼词库转全拼的方法

### ISSUE THREAD

**Issue by BenjaminX** [boomker/rime-fast-xhup#31]
不会双拼
这个项目带的词库可以用到全拼状态的Rime中吗？

**Comment by boomker** [comment]
有两种方法可以实现
1. 把词库中的注音全部去掉即可
2. 在`yaml`配置文件里写双拼到全拼的转换规则

**Comment by boomker** [comment]
小鹤转全拼规则
```yaml
  speller:
    alphabet: zyxwvutsrqponmlkjihgfedcba
    initials: zyxwvutsrqponmlkjihgfedcba
    delimiter: " '"
    algebra:
      - xform/^([bpmfdtnljqx])n/$1iao/
      - xform/^(\w)g/$1eng/
      - xform/^(\w)q/$1iu/
      - xform/^(\w)w/$1ei/
      - xform/^([dtnlgkhjqxyvuirzcs])r/$1uan/
      - xform/^(\w)t/$1ve/
      - xform/^(\w)y/$1un/
      - xform/^([dtnlgkhvuirzcs])o/$1uo/
      - xform/^(\w)p/$1ie/
      - xform/^([jqx])s/$1iong/
      - xform/^(\w)s/$1ong/
      - xform/^(\w)d/$1ai/
      - xform/^(\w)f/$1en/
      - xform/^(\w)h/$1ang/
      - xform/^(\w)j/$1an/
      - xform/^([gkhvuirzcs])k/$1uai/
      - xform/^(\w)k/$1ing/
      - xform/^([jqxnl])l/$1iang/
      - xform/^(\w)l/$1uang/
      - xform/^(\w)z/$1ou/
      - xform/^([gkhvuirzcs])x/$1ua/
      - xform/^(\w)x/$1ia/
      - xform/^(\w)c/$1ao/
      - xform/^([dtgkhvuirzcs])v/$1ui/
      - xform/^(\w)b/$1in/
      - xform/^(\w)m/$1ian/
      # - xform/^([aoe])\1(\w)/$1$2/
      - xform/^([aoe])\1/$1/
      - xform/^v/zh/
      - xform/^i/ch/
      - xform/^u/sh/
      - xform/^([jqxy])v/$1u/
```
