### ISSUE TITLE
word_append_space.lua 这个脚本如何移植到其他配置中？

### ISSUE THREAD

**Issue by dyphire** [boomker/rime-fast-xhup#33]
我在雾凇拼音的 https://github.com/iDvel/rime-ice/issues/327#issuecomment-1579699979 中看到了这个脚本，但在尝试以补丁方式添加到雾凇中时无法使脚本生效，想请问下如何正确移植这个脚本呢？

**Comment by boomker** [comment]
1. 需要在`rime.lua` 中添加
-- 适用于中文输入方案的中英文之间加空格
```lua
word_append_space = require("word_append_space")
word_append_space_filter = word_append_space.filter
word_append_space_processor = word_append_space.processor
```
2. 在主配置文件里引用这两个Lua功能
```yaml
    - lua_processor@word_append_space_processor
    - lua_filter@word_append_space_filter
```

---

另外你说的不生效，是指没有一点效果，还是在一些特定情况， 这个脚本还不是那么完美， 在一些情况下，用起来感觉像是没有效果的

**Comment by dyphire** [comment]
通过进一步研究这个配置中的写法。我通过以下补丁使它生效了
```yaml
patch:
  engine/processors/@before 0: lua_processor@word_append_space_processor
  engine/filters/+:
    - lua_filter@word_append_space_filter
    - uniquifier
```

但我在测试中发现输入英文时无论前面有没有输入中文它都会添加空格，这会是什么原因呢？
