### ISSUE TITLE
确认一下date_time.lua中的引用lua的影响

### ISSUE THREAD

**Issue by Hodwe** [boomker/rime-fast-xhup#51]
我在date_time.lua中删除了引用部分：local tool = require("tools/number_to_cn”)，想知道文章中还有哪些与引用有关的代码，想一起删除，担心后面报错受到影响，谢谢

下面是修改之后的代码，不确定是否还会受到删除引用lua产生的影响，谢谢

[date_time.txt](https://github.com/boomker/rime-fast-xhup/files/15365705/date_time.txt)

**Comment by boomker** [comment]
[date_time.lua.txt](https://github.com/boomker/rime-fast-xhup/files/15365934/date_time.lua.txt)

你试一下，看能用不

**Comment by Hodwe** [comment]
用了之后一直警告我这个，不知道咋回事：
```
W20240519 07:53:12.259644 0x1e49ba080 unity_table_encoder.cc:39] unity table encoder is not enabled in dict settings.
W20240519 07:53:14.056532 0x1e49ba080 unity_table_encoder.cc:39] unity table encoder is not enabled in dict settings.
W20240519 07:53:14.927831 0x1e49ba080 unity_table_encoder.cc:39] unity table encoder is not enabled in dict settings.
W20240519 07:53:15.542313 0x1e49ba080 unity_table_encoder.cc:39] unity table encoder is not enabled in dict settings.
W20240519 07:53:17.851521 0x1e49ba080 unity_table_encoder.cc:39] unity table encoder is not enabled in dict settings.
W20240519 07:53:27.580811 0x1e49ba080 unity_table_encoder.cc:39] unity table encoder is not enabled in dict settings.
W20240519 07:53:28.106004 0x1e49ba080 unity_table_encoder.cc:39] unity table encoder is not enabled in dict settings.
W20240519 07:53:42.162139 0x1e49ba080 unity_table_encoder.cc:39] unity table encoder is not enabled in dict settings.
W20240519 07:53:56.089093 0x1e49ba080 unity_table_encoder.cc:39] unity table encoder is not enabled in dict settings.
```

**Comment by boomker** [comment]
这个看起来，和 `Lua`  脚本没有关系，应该是 `YAML` 中的配置有问题。我没遇到过这种告警，不知道啥问题。

**Comment by Hodwe** [comment]
好的，lua成功了，谢谢，这个错误我也不知道咋回事，排除了好久，继续排除


Shingo ***@***.***>于2024年5月19日 周日11:12写道：

**Comment by Hodwe** [comment]
终于找到问题了，我将：

# 副翻译器：英文输入
melt_eng:
  dictionary: melt_eng # 挂载词库 melt_eng.dict.yaml
  spelling_hints: 5 # ～字以內候選標註完整帶調拼音
  enable_user_dict: true # 是否開啓用戶詞典〔用戶詞典記錄動態字詞頻、用戶詞〕
  db_class: userdb # 可設 tabledb〔文本〕或userdb〔二進制〕
  enable_encoder: true # 是否启用自动造词
  enable_sentence: false # 是否開啓自動造句  句子输入模式
  encode_commit_history: true # 自动造词功能
  enable_charset_filter: true # 开启字符集过滤
  enable_completion: true # 决定是否拓展英文单词
  initial_quality: 0.4 # 初始权重
  tips: ' 〔英文〕'
  comment_format: # 自定义提示码
    - xform/.*// # 清空提示码

中的：
enable_encoder: true # 是否启用自动造词
删除就正常了，不知道怎么回事

另外，大佬，我用的是雾凇拼音的全拼，麻烦帮我看看这个设置中有需要删除的吗？担心以后又出现问题，不太清楚每个具体功能是什么，谢谢（如果没时间，可以只看看translator和melt_eng，谢谢）

```
# 主翻译器，拼音
translator:
  dictionary: rime_ice # 挂载词库 rime_ice.dict.yaml
  spelling_hints: 0 # ～字以內候選標註完整帶調拼音
  contextual_suggestions: true # 开启八股文, 上下文联想
  enable_user_dict: true # 是否開啓用戶詞典〔用戶詞典記錄動態字詞頻、用戶詞〕
  db_class: userdb # 可設 tabledb〔文本〕或userdb〔二進制〕
  enable_encoder: true # 是否启用自动造词
  enable_sentence: true # 是否開啓自動造句 句子输入模式
  encode_commit_history: true # 自动造词功能
  enable_charset_filter: true # 开启字符集过滤
  enable_completion: false # 决定是否拓展汉字
  initial_quality: 1.2 # 拼音的权重应该比英文大
  preedit_format: # preedit_format 影响到输入框的显示和"Shift+回车"上屏的字符
    - xform/([jqxy])v/$1u/ # 显示为 ju qu xu yu
    # - xform/([nl])v/$1ü/    # 显示为 nü lü
    # - xform/([nl])ue/$1üe/  # 显示为 nüe lüe
    - xform/([nl])v/$1v/ # 显示为 nv lv
    - xform/([nl])ue/$1ve/ # 显示为 nve lve

# 自定义短语：custom_phrase.txt
custom_phrase:
  dictionary: ''
  user_dict: custom_phrase
  db_class: stabledb
  enable_completion: false # 补全提示
  enable_sentence: false # 禁止造句
  initial_quality: 99 # custom_phrase 的权重应该比 pinyin 和 melt_eng 大

# 副翻译器：英文输入
melt_eng:
  dictionary: melt_eng # 挂载词库 melt_eng.dict.yaml
  spelling_hints: 5 # ～字以內候選標註完整帶調拼音
  enable_user_dict: true # 是否開啓用戶詞典〔用戶詞典記錄動態字詞頻、用戶詞〕
  db_class: userdb # 可設 tabledb〔文本〕或userdb〔二進制〕
  enable_encoder: true # 是否启用自动造词
  enable_sentence: false # 是否開啓自動造句  句子输入模式
  encode_commit_history: true # 自动造词功能
  enable_charset_filter: true # 开启字符集过滤
  enable_completion: true # 决定是否拓展英文单词
  initial_quality: 0.4 # 初始权重
  tips: ' 〔英文〕'
  comment_format: # 自定义提示码
    - xform/.*// # 清空提示码

# emoji表情反查
emoji_suggestion:
  opencc_config: emoji.json
  option_name: emoji_suggestion
  show_in_comment: false
  comment_format:
    - 'xform@_@ @'
  tags:
    - rime_ice_emoji
  tips: all

#emoji表情反查
rime_ice_emoji:
  tag: rime_ice_emoji
  dictionary: rime_ice
  enable_completion: false # 决定是否拓展表情
  enable_user_dict: true # 是否開啓用戶詞典〔用戶詞典記錄動態字詞頻、用戶詞〕
  db_class: userdb # 可設 tabledb〔文本〕或userdb〔二進制〕
  enable_encoder: true # 是否启用自动造词
  enable_sentence: true # 是否開啓自動造句  句子输入模式
  enable_charset_filter: true # 开启字符集过滤
  encode_commit_history: false # 是否对已上屏词自动成词（仅 table_translator 有效）
  max_phrase_length: 15 # 自动成词的最大词长
  prefix: '`'
  tips: ' 〔表情〕'
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/

reverse_lookup:
  tag: reverse_lookup
  prefix: '/' # 反查引导符「;」
  enable_charset_filter: true # 开启字符集过滤
  tips: ' 〔雾凇&拆字&笔画〕'
  extra_tags:
    - rime_ice_lookup
    - radical_pinyin_lookup
    - stroke_lookup

rime_ice_lookup:
  tag: rime_ice_lookup
  dictionary: rime_ice
  enable_completion: true # 决定是否拓展汉字
  enable_user_dict: false # 是否開啓用戶詞典〔用戶詞典記錄動態字詞頻、用戶詞〕
  enable_sentence: false # 是否開啓自動造句  句子输入模式
  encode_commit_history: false # 是否对已上屏词自动成词（仅 table_translator 有效）
  enable_encoder: true # 是否启用自动造词
  enable_charset_filter: true # 开启字符集过滤
  prefix: '/W'
  tips: ' 〔雾凇〕'
  initial_quality: 0.1

radical_pinyin_lookup:
  tag: radical_pinyin_lookup
  dictionary: radical_pinyin
  enable_completion: true # 决定是否拓展汉字
  enable_user_dict: false # 是否開啓用戶詞典〔用戶詞典記錄動態字詞頻、用戶詞〕
  enable_sentence: false # 是否開啓自動造句  句子输入模式
  encode_commit_history: false # 是否对已上屏词自动成词（仅 table_translator 有效）
  enable_encoder: true # 是否启用自动造词
  enable_charset_filter: true # 开启字符集过滤
  prefix: '/C'
  tips: ' 〔拆字〕'
  initial_quality: 0.7

stroke_lookup:
  tag: stroke_lookup
  dictionary: stroke
  enable_completion: true # 决定是否拓展汉字
  enable_user_dict: false # 是否開啓用戶詞典〔用戶詞典記錄動態字詞頻、用戶詞〕
  enable_sentence: false # 是否開啓自動造句  句子输入模式
  encode_commit_history: false # 是否对已上屏词自动成词（仅 table_translator 有效）
  enable_encoder: true # 是否启用自动造词
  enable_charset_filter: true # 开启字符集过滤
  prefix: "/B"
  tips: ' 〔笔画〕'
  initial_quality: 0.75
  preedit_format:
    - 'xform/^([hspnz]+)$/$1\t（\U$1\E）/'
    - xlit/HSPNZ/一丨丿丶乙/

rime_ice_reverse_lookup:
  tags: [rime_ice, rime_ice_lookup]
  dictionary: triple
  overwrite_comment: true # 覆盖其他提示

radical_pinyin_reverse_lookup:
  __include: rime_ice_reverse_lookup
  tags: [radical_pinyin_lookup]

stroke_reverse_lookup:
  __include: rime_ice_reverse_lookup
  tags: [stroke_lookup]
```
